Feature/JC19-353-table-view
saritasa-nest/camp-js-2022-khoa-nguyen pull request #1
Opened 2022-07-07 06:18 UTC by khoanguyen-saritasa

Initialize Anime app and table view with Vanilla JS/HTML/CSS.

2022-07-07 09:07 UTC, TienLuu-Saritasa requested changes

2022-07-07 09:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.ts
> +function formatDate(str: Date): string {
What is `str`? Please [avoid contraction](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-07-07 09:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.ts
> +function renderRangeOfPagination(activePage: number, from: number, to: number): string {
> To increase the cohesion of these pagination-related properties, it would be reasonable to unify them into a single entity. Also, [we prefer avoiding ordered params](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#how-to-pass-arguments-to-functionsmethods).

2022-07-07 09:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.ts
> +  if (activePage < 5) {
Please avoid magic number, i don't know `5` used for what

2022-07-07 10:47 UTC, thanhnguyen-saritasa commented on libs/core/enum/enum.ts
> +
I think we can make different name for this file. It could be "anime.ts"
It will be better when we can have another enums

2022-07-07 10:55 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +  gap: 40px;
Does it already has display flex/ grid?
I know using 'gap' with flex / grid
https://developer.mozilla.org/en-US/docs/Web/CSS/gap

2022-07-07 13:42 UTC, timofei-maximov-saritasa requested changes

2022-07-07 13:42 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/configs/axiosConfig.ts
> +});
I think you can just add `api-key` to axios config.

2022-07-07 13:42 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/interface/sortInterface.ts
> +  readonly api: string;
`api` is not a good name. I would suggest using something like this:
```ts
interface Sort {
  readonly title: string;
  readonly value: string;
}
```

2022-07-07 13:42 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +          <select id = "selectSort">
Extra space
```suggestion
          <select id="selectSort">
```

2022-07-07 13:42 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/fetchAnimeList.ts
> +export async function asyncFetchAnimeList(limit: number, offset: number, ordering: string): Promise<Pagination<Anime>> {
There is no need to add `async` for function name

2022-07-07 14:04 UTC, TienLuu-Saritasa requested changes

2022-07-08 06:15 UTC, golovachev-yaroslav requested changes

2022-07-08 06:15 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +.container__list_item .img > img {
`.img` looks like a wrapper, need to rename or add a class for tag img, `.img > img` looks strange.

2022-07-08 06:15 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +  font-size: large !important;
I believe you can find a solution how to avoid `!important`

2022-07-08 06:15 UTC, golovachev-yaroslav commented on libs/core/dtos/anime.dto.ts
> +import { StatusEnum, TypeEnum } from '../enum/enum';
Too many words `enum`, it would be better to renmae.

2022-07-08 06:16 UTC, khoanguyen-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      airedStart: dto.aired.start !== null ? new Date(dto.aired.start) : null,
As I learned about the code, this file is used to map dtos from back-end into the data used in Front-end. The last line is used to convert the type of airedStart from string (this is the type we received from back-end) to Date.

2022-07-08 06:19 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +  gap: 40px;
Sorry I forgot removing gap after deleting display:flex in my code.

2022-07-08 09:20 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/configs/axiosConfig.ts
> +export const appAxios: AxiosInstance = axios.create({
Unnecessary type annotation

2022-07-08 09:20 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  font-size: 25px;
Please use variables for font related properties.

2022-07-08 09:20 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.ts
> +  const PAGE_AT_INDEX_5_REVERSE = totalPage - 4;
Please think a better names, if I understand your idea correctly, something like `PAGINATION_PAGES_COUNT` would be better. If you can't came up with better name, leave a explaining comments in code.

2022-07-08 09:20 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/anime.dto.ts
> +}
I suggest moving it in it's own file.

2022-07-08 09:20 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      }),
I suggested to extract DateRange in it's own file, so extract DateRange mapper too

2022-07-08 17:07 UTC, TienLuu-Saritasa requested changes

2022-07-08 17:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/interface/paginationInterface.ts
> +  title: SortTitle;
```suggestion
  readonly title: SortTitle;
```
[Promote immutability](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices/#promote-immutability)
As we already suggested in [code practices section](https://wiki.saritasa.rocks/frontend/practices/code#promote-immutability), you should always make sure you're operating with immutable data objects. Typescript allows to explicitly declare more data this way, that is exactly what we need 🐱‍🏍.

Use readonly as much as you use const in order to explicitly declare the variables/properties immutable.

If you want to change your value, please use [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#examples). Feel free to ping me anytime in case you have any questions or suggestions

2022-07-08 17:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/scripts/fetchAnimeList.ts
> +// }
Please remove your comment

2022-07-11 07:01 UTC, elena-dragunova approved these changes

2022-07-11 08:14 UTC, panov-aleksey-saritasa requested changes

2022-07-11 08:14 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/interface/sortInterface.ts
> +
Extra empty line + as I said there is no need to add `interface` to the docs. Also there is no need to add it to the file name, the `interface` folder implies by itself that it consists of interfaces, right?

2022-07-11 08:14 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +.container__filter_item {
If you are using [BEM](https://en.bem.info/methodology/), please, read about [modifiers](https://en.bem.info/methodology/key-concepts/#modifier). `item` is definitely not a modifier

2022-07-11 08:14 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <div class="container__table">
Is it list or table 🤔?
And as I saw, you add table `HTML` here and your resulting template has the following structure:
```html
<div class="container__table">
  <table>
    ...
   </table>
</div>
```
So `container__table`  is actually not a table element but some kind of layout wrapper. Do you need it in the first place? If yes, consider revising your css style naming

2022-07-11 08:14 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +  height: 200px;
Rather than hardcode `width`/`height`, consider using more flexible and robust approach with `min-height(width)`/`max-height(width)`.
We have the section about it in [wiki](https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size)
Also you could check this article https://ishadeed.com/article/defensive-css/, it contains section about hardcoded sizes, but also has some useful advices about css styling overall

2022-07-12 09:55 UTC, thanhnguyen-saritasa approved these changes

2022-07-12 21:16 UTC, chernodub requested changes

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +    <!-- Compiled and minified CSS -->
It is already obvious that this stylesheet is minified, from the name of the asset. Please consider omitting obvious comments at all times

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +        <div class="filter__item">
Please revise BEM docs. Elements can not exist without blocks :)

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +          <select class="select select__sort">
Your `select` is nested in `select__title` element. It must not be possible, please re-structure this

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +          <h2 class="select__title">Ordering by</h2>
This should be [`label`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), not `h2`. We use labels for captioning controls, h2 for captioning sections of content.

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +const animeListInitial = await fetchAnimeList(INITIAL_PAGINATION);
Top-level `await` still has [poor support across browsers](https://caniuse.com/?search=top%20level%20await). Please be careful with this on your production projects.

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/scripts/fetchAnimeList.ts
> +    return new Error(`Failed to get anime list: ${errors as string}`);
Errors must not be returned, they must be thrown via `throw` syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +          <th class="item_col wrapper__img" style="background-image: url(${element.image}) ;" ">
This line is invalid HTML, contains double `"` syntax at the end

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +          <th class="item_col wrapper__img" style="background-image: url(${element.image}) ;" ">
Please stick to block > modifier structure like BEM specification suggests. I strongly recommend revising the BEM docs

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +    const htmlInsideContainer = animeList.results.map(element => (
I recommend making this property name more specific for the use case and semantically valuable. As far as I see, this represents a body of the table, not just HTML in some container :)

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +      <caption>Anime list</caption>
`caption` must always be inside a `table`

2022-07-12 21:16 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +    throw new Error(`Unable to render Anime list ${error as string}`);
Wrong casting of `error` variable, it is instance of `Error` not string. Please [avoid type-casting](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-non-null-and-type-assertions)

2022-07-13 04:10 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-13 06:03 UTC, khoanguyen-saritasa commented on apps/vanilla/src/interface/sortInterface.ts
> +export interface Sort {
Thank you for your review, but in my case this is just a normal interface for my constant sorting, which not relates with the API so using the DTO might not be suitable in this situation.

2022-07-15 04:26 UTC, TienLuu-Saritasa approved these changes

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/initAnimeTable.ts
> + */
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-inline-when-possible

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/enum/anime.ts
> +  // NotYetAir = 'NOT_YET_AIRED',
Don't forget to remove it

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly status: keyof Status;
This won't work. 
```ts
readonly status: keyof typeof Status
```

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly type: keyof Type;
It seems like you violated abstraction. If your `Type` is a part of you domain, then `AnimeDto` can't contain `Type`. It should be either string or `TypeDto`

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/mappers/paginationOptions.mapper.ts
> +      // ordering: options.sorting.value,
Don't leave commented code

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/utils/index.ts
> +}
I don't think that this should be located in your shared code, since angular/react app won't use it.

2022-07-16 09:36 UTC, timofei-maximov-saritasa commented on libs/core/dtos/dateRange.dto.ts
> +  readonly end: string;
These fields are nullable according to api documentation

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/utils/index.ts
> +  return newDate.toLocaleDateString('en-us');
Why do you need `newData`? Why not just `return dateToFormat.toLocaleDateString('en-us');`?

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/enum/anime.ts
> +  DEFAULT = '',
Please, use `CamelCase` here like you do for other enums

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      aired: DateRangeMapper.fromDto({ start: dto.aired.start, end: dto.aired.end }),
```suggestion
      aired: DateRangeMapper.fromDto({  ...dto.aired }),
```

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/models/anime.ts
> +  public readonly titleJapan: string;
Japan -> Japanese

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/models/sorting.ts
> +  public readonly value: SortValue;
It's not clear what is *name of sorting* and how it's different from *title of sorting*. Please, improve docs

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on libs/core/models/paginationOptions.ts
> +
Actually, `sorting` is a thing unrelated to `pagination`. Please, separate them

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +        <select class="filter__item_select filter__item_select-sort"></select>
Associate `label` with `select` to improve accesability
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2022-07-18 10:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/service/localStorage.ts
> +}
There is no need to duplicate `LocalStorage` context each time. Consider using namespace or class instead:
```ts
export namespace LocalStorage {
  export function getValue(...)
  export function setValue(...)
  export function removeKey(...)
}
```

2022-07-19 12:36 UTC, pavelzadorin-saritasa requested changes

2022-07-19 12:36 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +/** Init and render sorting and ordering list, hence render corresponding list anime.
for multi-line comments, the documentation is placed on the second line: https://jsdoc.app/about-getting-started.html

2022-07-19 12:36 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +    .join('');
extra line break

2022-07-19 12:36 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +      const { value } = selectSort;
please check the indentation throughout the file

2022-07-19 12:36 UTC, pavelzadorin-saritasa commented on libs/core/mappers/dateRange.mapper.ts
> +   * @param dto Genre dto.
incorrect docstring

2022-07-19 12:36 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    const animeList = await fetchAnimeList(optionUpdated);
setting `AnimeListQueryOptions` happens several times and the method to get Anime is called 2 times, I'm sure this can be simplified and call api only 1 time, I would suggest setting `optionUpdated` and `fetchAnimeList` just into `initAnimeTable.ts`, and this method will receive as a parameter a ready-made `animeList` just to draw the table.
I think then in `initAnimeTable.ts` you will be able to understand how you can optimize the parameter setting.

2022-07-25 07:29 UTC, pavelzadorin-saritasa approved these changes
I looked at your fixes, they are accepted.
But you don’t need to make fixes in another review, this makes it very difficult to work with a code review.
First, we try to break the work into small tasks, including in order to get small reviews. Studying a 5 small review with 1 feature each is much easier than a large review with 5 features. You now have a review of details, this is just such a big review with 5 features, for example, I will hardly have time to study it in full :(
Secondly, it is very difficult to control what was fixed and how, I need to jump between different reviews, and if the fix is ​​not done as it should, should I write a new comment in `detail page` review or continue the communication here?
As it was necessary to do, make fixes according to the comments from the `table` directly in this branch, so that in this review we can see what and how is corrected, and then merge these fixes to the `detail page` branch, then in the `detail page` branch you would have the latest version all fixes of the `table`, but only changes related specifically to the specific feature would get into their review.

2022-07-28 04:34 UTC, chernodub requested changes

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/constants/sortOptions.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
@khoanguyen-saritasa seems like this comment is resolved without a fix. _If you received a comment with which you do not agree, you must not resolve it silently. Answer it, and make sure the person who left the comment agreed with you (or vice-versa). Only then a comment may be considered as resolved._ Please check out our best practices in code reviews https://wiki.saritasa.rocks/general/git#code-review

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +            <img class= "table__row_item_thumb__img" src="${element.image}" alt="${element.titleEnglish}" />
Seems like this is a wrong usage of BEM. You can not have nested elements (e.g: `block__element__element` is forbidden). Please, revise BEM docs or check out this [cheat sheet](https://9elements.com/bem-cheat-sheet/).

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/pages/index.css
> +  opacity: 0;
Do you still need the spacing provided by this caption element? If not, consider checking out [this technique](https://medium.com/web-dev-survey-from-kyoto/the-visually-hidden-technique-303f8e2bd409). It allows you to hide an element visually, but make sure it is still visible for the screen readers

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +      </div>
I'd recommend revising your BEM structure here, like I mentioned, you can check out the BEM cheat sheet, it provides a very understandable visual explanation of how block/element/modifier should work together :)

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +      </div>
[cheat sheet](https://9elements.com/bem-cheat-sheet/)

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    return animeList;
I see that you never use this value, probably your render function should not return these values then.

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderPagination.ts
> +    }
I saw this error mapping several times, please consider reusing this logic by creating a function

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderPagination.ts
> +      });
I see you add event listeners but never remove them, this is a memory leak. As far as I understand, if this listener is called several times, it's going to produce a bunch of others, they will all be called whenever I click to a `li`

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderPagination.ts
> +      item.addEventListener('click', () => {
[Please use buttons for handling user clicks](https://wiki.saritasa.rocks/frontend/languages/html#use-button-for-handling-user-clicks)

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +  setDefaultSelected(selectSort, LocalStorageService.getValue<Sorting>(KEY_SORTING)?.title ?? SORT_OPTIONS[0].title);
Consider reducing the line length in your code, this will make it more readable. Feel free to create variables where you would put your values that you are obtaining inline (like `LocalStorageService.get...`, this will also make your code more documented. Check out [self-documenting code](https://en.wikipedia.org/wiki/Self-documenting_code#:~:text=In%20computer%20programming%2C%20self%2Ddocumenting,system%20without%20prior%20specific%20knowledge.)

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +  const orderOptionHTML = Object.keys(OrderOption).map(item => (
This is a list of options, let's make the variable name more explicit. https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#singular-and-plurals

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +  if (selectOrdering === null || selectOrdering === undefined) {
This would do the same
```suggestion
  if (selectOrdering == null) {
```

2022-07-28 04:34 UTC, chernodub commented on apps/vanilla/src/utils/index.ts
> +    }
But your type declaration tells me that this could never be "nullable", only `string`. Please be consistent :)

2022-07-28 04:34 UTC, chernodub commented on libs/core/dtos/anime.dto.ts
> +  readonly modified: string;
As far as I understand, both of these values should be `string` dates

2022-07-28 04:34 UTC, chernodub commented on libs/core/dtos/dateRange.dto.ts
> +  readonly end: string;
@khoanguyen-saritasa please do not resolve the comments without either answering or fixing the code

2022-07-28 16:15 UTC, khoanguyen-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    return animeList;
This value is used in renderListOnActivePage.ts file, in the line of 106. I used this value to get the information of total anime items in the list, therefore rendering the corresponding pagination of each query.

2022-07-28 16:17 UTC, khoanguyen-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly modified: string;
Yes that was my mistake.

2022-07-28 16:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      </div>
Hi Viktor, it's my fault when fixing all your code reviews in another pull request (which is displaying anime detail) and resolving the comments in this pr. Pavel also reminded me the disadvantages of doing that and I have learned deeply from him. :( Sorry for wasting your effort and time in this pr.

2022-07-28 16:55 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      </div>
I have updated all my codes base on your reviews (includes editing css class with BEM and removing event listeners). Hope you can take a look at them. And of course this time I did it in this PR so don't worry. 😄

2022-08-02 04:47 UTC, chernodub approved these changes

2022-08-03 04:48 UTC, merged