Feature/JC19-433-angular-authorization
saritasa-nest/camp-js-2022-khoa-nguyen pull request #11
Opened 2022-08-09 08:36 UTC by khoanguyen-saritasa

2022-08-11 06:33 UTC, panov-aleksey-saritasa requested changes

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/authorization/login/login.component.html
> +    <h1 class="login__title login__title_action">Login to your account</h1>
Please, avoid using multiple `<h1>` tags. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#multiple_h1_elements_on_one_page

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/authorization/register/register.component.css
> +.register {
Seems like duplication of styles from [login component](https://github.com/saritasa-nest/camp-js-2022-khoa-nguyen/blob/6d03ab73db1508973901090c80c6b6909e390a7d/apps/angular/src/app/features/authorization/login/login.component.css). Can you do something to avoid code duplication?

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/authorization/login/login.component.ts
> +      .subscribe();
I suppose `takeUntil(this.subscriptionManager$)` would not work by itself, you have to add additional logic on component unmount
```ts
 /** @inhericdoc */
  ngOnDestroy() {
    this.subscriptionManager$.next();
    this.subscriptionManager$.complete();
  }
```

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/authorization/login/login.component.ts
> +          this.localStoreService.setValue<Token>(key.token, value);
I don't think it's a good idea to do token management in your UI layer, could delegate this kind of stuff to your domain services?

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/guards/nonNullField.guard.ts
> +}
```suggestion
export function isDefined<T>(value: T | null | undefined): value is T {
  return value != null;
}
```

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +      .subscribe();
In services we do not subscribe to observables, but rather return them, so that service consumers could work with streams directly.

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/navigation/navigation.component.css
> +  z-index: 10;
https://wiki.saritasa.rocks/frontend/languages/css#explain-why-tricks-are-used-z-index-important

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +    private readonly animeService: AnimeService,
```suggestion
    private readonly router: Router,
    private readonly animeService: AnimeService,
```

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +  public isLoggedIn$ = this._isLoggedIn$.asObservable();
Please, do not forget about `readonly`. Usually we do not reassign streams

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/navigation/navigation.component.ts
> +  }
On Angular projects we usually use `on` prefix for event handlers method names
```suggestion
  /** Handle logout.*/
  public onLogOutButtonClick(): void {
    this.authService.logout();
  }
```

2022-08-11 06:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/navigation/navigation.component.html
> +      <a *ngIf="(isAuth$| async) === false" [routerLink]="['/auth/register']" class="navigation__link">Sign up</a>
Usually we use `<a>` tag for navigation purposes and `<button>` when we need to do some logic on click, try to not mix these things up.

2022-08-12 03:13 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +        [ngStyle]="{ paddingLeft: 0 }"
I cannot overwrite the style of **Angular material table** by using only CSS classes. Therefore, I have to use to use the inline one for such purpose.

2022-08-18 10:16 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-18 10:18 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +        [ngStyle]="{ paddingLeft: 0 }"
It happens because angular uses `element.class` notation in the styles, it has slightly bigger specificity than just `.class`. I think in such cases it's okay to use `!important`

2022-09-26 02:49 UTC, closed without merging