Feature/JC19-463-react-initial-authorization-anime
saritasa-nest/camp-js-2022-khoa-nguyen pull request #14
Opened 2022-08-25 04:20 UTC by khoanguyen-saritasa

2022-08-25 10:43 UTC, golovachev-yaroslav requested changes

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/api/services/tokenService.ts
> +  export async function isValid(token: Token) {
Missed return type.

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/components/Button/index.tsx
> +interface Props {
In think need to extend HTMLButtonElement.

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/components/Button/index.tsx
> +  onClick,
Looks like missed recent props
`...props`

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/components/Button/index.tsx
> +    onClick={onClick}
Need to add {...props} oherwise impossible to pass another props: disabled, form, etc

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/FormItem/index.tsx
> +        {...field}
{...field}
{...propsInput}
Should be the first, otherwise they could override `label`, `type` props if passed in {...field} or {...propsInput}

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/login/index.tsx
> +    // navigate((state as StateLocation).path ?? '/');
Please remove if you don't use or leave a comment.

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/layout/defaultLayout/index.tsx
> +  <div>
It could be `<> </>`, not required.

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/store/anime/dispatchers.ts
> +  'auth/login',
Looks like wrong name, maybe `anime/getAnimeList` ?

2022-08-25 10:43 UTC, golovachev-yaroslav commented on apps/react/src/store/anime/slice.ts
> +        // state.animeList = action.payload;
Maybe remove?

2022-08-25 13:11 UTC, gevorg-gevorgyan-saritasa commented on apps/react/src/store/auth/state.ts
> +  /** Whether the token are loading or not. */
```suggestion
  /** Whether the token is loading or not. */
```

2022-08-25 13:11 UTC, gevorg-gevorgyan-saritasa commented on apps/react/src/api/interceptors/refreshToken.ts
> +export async function refreshToken(error: unknown) {
I see that you missed return type in a lot of your functions. Could you fix it please?

2022-08-26 02:38 UTC, khoanguyen-saritasa commented on apps/react/src/api/interceptors/refreshToken.ts
> +export async function refreshToken(error: unknown) {
Yeah sure, thank you for remind me.

2022-08-26 05:11 UTC, golovachev-yaroslav requested changes

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/components/Button/index.tsx
> +import _style from './Button.module.css';
Why it start with `_` symbol? Lets call it just `style`.

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/components/Card/index.tsx
> +  // eslint-disable-next-line jsdoc/require-jsdoc
PLease add jsdoc instead of eslint-disable

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/components/PreventAuth/index.tsx
> +  // eslint-disable-next-line jsdoc/require-jsdoc
THe same with jsdoc.

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/login/index.tsx
> +const validationSchema: yup.SchemaOf<LoginModel> = yup.object().shape({
It would be better to move validation settings, initial state into a separate file, ex: formSettings.ts.
It makes code more clear.

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/register/index.tsx
> +
PLease remove empty line.

2022-08-26 05:11 UTC, golovachev-yaroslav commented on apps/react/src/layout/header/index.tsx
> +      <Button onClick={handleLogout} >Log out</Button>
Missed button type.
I think you could add `type="button"` by default in `Button` component.

2022-08-26 07:18 UTC, khoanguyen-saritasa commented on apps/react/src/App.tsx
>        <div>
I think it's redundant but it's in React project base config. Well let just remove it I think :D

2022-08-26 11:00 UTC, timofei-maximov-saritasa commented on apps/react/src/store/auth/slice.ts
> +      .addCase(login.rejected, (state, action) => {
You can specify action type to avoid type-casting. Use `PayloadAction` type. It accepts generic

2022-08-26 11:00 UTC, timofei-maximov-saritasa commented on apps/react/src/store/auth/state.ts
> +  readonly isAuth: boolean;
`isAuth` is a bit confusing for me. `isAuthorized` sounds better.

2022-08-30 05:42 UTC, golovachev-yaroslav requested changes

2022-08-30 05:42 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/pages/anime-table/index.tsx
> +          <Card>Test</Card>
Is it a temporary layout? What should be instead of Test?

2022-08-30 05:42 UTC, golovachev-yaroslav approved these changes

2022-08-30 06:34 UTC, khoanguyen-saritasa commented on apps/react/src/features/anime/pages/anime-table/index.tsx
> +          <Card>Test</Card>
Yeah this is just a temporary layout (or placeholder) for anime table implementation on the next task.

2022-08-30 10:07 UTC, pavelzadorin-saritasa requested changes

2022-08-30 10:07 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/pages/register/index.tsx
> +      <Snackbar
You repeat Snackbar configuring and implementation logic in each forms, I would like to avoid code repetition.
So encapsulation of the Snackbar display logic inside the additional Snackbar component looks reasonable, at the moment the parent component (e.g. RegisterForm) define the Open status and CloseHandler and passes them to the Snackbar, but really does the parent need to operate with these entities at all? why can't the Snackbar manage the opening status itself internally and handle the closing? From the parent, then only the message and type of error will be needed, well, maybe HideDuration yet and the forms will become much simpler.
May be conditional rendering will be enough for opening Snackbar:
```
{error &&
  <MySnackbar
        message={error}
        severity='error'
    />
}
```
Even more, I've found, that MUI recomend this library to simplify snackbar notifications (you can share this with other guys :) https://mui.com/material-ui/react-snackbar/#notistack

2022-08-31 03:47 UTC, khoanguyen-saritasa commented on libs/core/models/login.ts
> +export type LoginModel = OmitImmerable<Login>;
The login form has the similar type with login model. That's why I thought I can reuse this type for my login form. Is it okay or I should not do that?

2022-08-31 03:52 UTC, khoanguyen-saritasa commented on libs/core/models/login.ts
> +export type ErrorLoginType = OmitImmerable<ErrorLogin>;
Actually this one is redundant. I don't know why I accidentally wrote the export for it. :(

2022-08-31 04:04 UTC, khoanguyen-saritasa commented on apps/react/src/features/auth/pages/login/index.tsx
> +  const [isShowBackendError, setIsShowBackendError] = useState<boolean>(false);
Since there was a snackbar displaying the error, this useState is redundant. It's my fault cause I forgot removing it :(

2022-09-05 06:11 UTC, pavelzadorin-saritasa commented on libs/core/models/login.ts
> +export type LoginModel = OmitImmerable<Login>;
So why can't you use `Login` directly in the form?
Like this: http://jing.saritasa.com/PavelZadorin/screen_2022-09-05_13-08-02_NvJu.png
What disadvantages do you see in this approach?

2022-09-05 07:17 UTC, khoanguyen-saritasa commented on libs/core/models/login.ts
> +export type LoginModel = OmitImmerable<Login>;
Oh :v There is no disadvantage in that approach as far as I can see. Maybe I was overthinking about this issue. :( I don't know why I use such an unsuitable way for an easy case :(

2022-09-05 16:14 UTC, pavelzadorin-saritasa approved these changes

2022-09-05 16:14 UTC, pavelzadorin-saritasa commented on libs/core/models/login.ts
> +  public constructor(data: LoginModel) {
Let's rename them back to `...InitArgs` to eliminate confusion about which one is a model, and which is just an internal utility type for the constructor.

2022-09-26 02:46 UTC, merged