Feature/JC19-473-react-anime-list-feature
saritasa-nest/camp-js-2022-khoa-nguyen pull request #15
Opened 2022-08-25 08:54 UTC by khoanguyen-saritasa

2022-08-25 10:11 UTC, golovachev-yaroslav requested changes

2022-08-25 10:11 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeItem/AnimeItem.module.css
> +  overflow: visible !important;
!important is not so good. Is it possible to find another way how to avoid important? 
Maybe `.parent .child {...` or `.anime-item__wrapper[class*="Mui-..."]` or another.

2022-08-25 10:11 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeSidebar/index.tsx
> +import React, { useEffect } from 'react';
Usually import external libs and then developer's.

2022-08-25 10:11 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/pages/AnimeTable/index.tsx
> +      />
Do not leave `/>` on the next line, it would be better `<AnimeSidebar />`

2022-08-25 10:46 UTC, golovachev-yaroslav approved these changes

2022-08-26 05:13 UTC, golovachev-yaroslav approved these changes

2022-08-26 06:13 UTC, golovachev-yaroslav approved these changes

2022-08-26 06:13 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeSidebar/index.tsx
> +    const option = {
It would be better move out the component to prevent rerender it.

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa requested changes

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/api/services/animeService.ts
> +  export async function getAnimeList(params: any): Promise<Pagination<Anime>> {
Don't use `any`, please create a type for params

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeInfinitiveScroll/index.tsx
> +import { getAnimeList, getNextAnimeList } from '@js-camp/react/store/anime/dispatchers';
"Infinitive" is a linguistic term, I think you need "infinite"

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeInfinitiveScroll/index.tsx
> +  if (isLoading) {
Please, pay more attention to code formatting. Use empty lines to group your code into code blocks.
```suggestion
  useEffect(() => {
    const observer = new IntersectionObserver(handleObserver, option);
    if (itemRef.current) {
      observer.observe(itemRef.current);
    }
    return () => {
      observer.disconnect();
    };
  }, [handleObserver]);
 
  if (isLoading) {
```

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/Tabs/index.tsx
> +          <Fragment>{item.panel}</Fragment>
Please be consistent with fragments syntax. I seen that you used `<>...</>`, so choose one syntax and use it everywhere.

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/index.tsx
> +export const AnimeSearchInner: React.FC = () => {
Again, be consistent, and prefer importing instead of accessing `FC` from `React` object.

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/index.tsx
> +        placeholder="Ex: Naruto, ..."
"Ex" is a wrong term, it means exercise, you should use "e.g.". I know it's a bit tricky, because it Latin terms, but try to remember it 😉.

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/hooks/useEffectSkipFirstRender.ts
> +    callback?.();
Do you really need `?.` here?

2022-08-30 04:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/services/searchParamService.ts
> +  readonly sortBy?: SortValue;
You shouldn't mix abstraction layers, here you use model and dto in the same interface.

2022-08-30 07:20 UTC, golovachev-yaroslav approved these changes

2022-08-30 08:21 UTC, khoanguyen-saritasa commented on apps/react/src/api/services/animeService.ts
> +  export async function getAnimeList(params: any): Promise<Pagination<Anime>> {
Actually, get anime list with param belongs to next task, which is anime list management. I forgot checking out to a new branch when implementing this feature :( Sorry about that. This is why param variable has an any type but not param type because I just only made a test (checking whether it's working or not) of this feature.

2022-08-30 08:32 UTC, khoanguyen-saritasa commented on apps/react/src/services/searchParamService.ts
> +  readonly sortBy?: SortValue;
Thank you for reminding me but this search param service also belongs to the next task, which is anime list management :( Again it's my fault because of forgetting checking out to another branch. I will fix this in the next pr and for this one, I will remove it to avoid confusion. Is that oke?

2022-09-02 04:37 UTC, panov-aleksey-saritasa requested changes

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeInfiniteScroll/AnimeInfiniteScroll.tsx
> +          <AnimeItem data={item} />
I am not sure how it works, but you probably should add `ref` only for the last element in the list

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeInfiniteScroll/AnimeInfiniteScroll.tsx
> +      <div>{nextPage && <LoadingComponent />}</div>
I think you should display loading not when there are more pages to load, but rather if the next page is actually in the loading state

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeItem/AnimeItem.tsx
> +        <Typography>Type: {data.type || '--'}</Typography>
Let's not repeat ourselves and move this `|| '--'` stuff into separate function

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeItem/AnimeItem.tsx
> +      )}
Maybe you could add some fallback image to display in case if there is no `image` in anime model for some reason

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/AnimeSearch.tsx
> +        placeholder="e.g.Naruto, ..."
Does the BE supports multiple anime search via separation by comma? If not let's change it to not confuse your users
```suggestion
        placeholder="e.g. Naruto"
```

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeSidebar/AnimeSidebar.tsx
> +  <ListItem className={style['anime-sidebar']}>
Since it's a sidebar, let's be more semantically correct
```suggestion
  <ListItem component="aside" className={style['anime-sidebar']}>
```

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeSidebar/AnimeSidebar.tsx
> +  <ListItem className={style['anime-sidebar']}>
BTW, why it's `ListItem`? Maybe it should be `List` instead?

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/hooks/useEffectSkipFirstRender.ts
> +  const isFirstMounted = useRef(0);
I think it's confusing that `number` ref has a name as if it's a `boolean`. Let's improve it

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/hooks/useEffectSkipFirstRender.ts
> +    if (isFirstMounted.current < 2) {
Why `2`? Wouldn't actually 2 renders be skipped?

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/AnimeSearch.tsx
> +  }, [debounceValue]);
It would be great if you provided docs about why do you need to skip first render

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/hooks/useSearch.ts
> +    }, 300);
Let's avoid magic numbers

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/store/anime/dispatchers.ts
> +  async(param: any, { rejectWithValue }) => {
Why `any`?

2022-09-02 04:37 UTC, panov-aleksey-saritasa commented on apps/react/src/store/anime/state.ts
> +  readonly nextPage: string | null;
Why page could have `string` type? If it's not a mistake, let's improve docs and naming

2022-09-05 03:04 UTC, khoanguyen-saritasa commented on apps/react/src/api/services/animeService.ts
> +    const paginationDto = await http.get(ANIME_LIST_URL, { params: params !== '' ? params : undefined });
This was my mistake since I forgot removing the param of getAnimeList function in this pull request after testing the search query (which will be implemented in the next pr). I will remove all of them out of this pr to avoid confusion.

2022-09-05 03:07 UTC, khoanguyen-saritasa commented on apps/react/src/store/anime/dispatchers.ts
> +  async(param: any, { rejectWithValue }) => {
This was my mistake since I forgot removing the param of getAnimeList function in this pull request after testing the search query (which will be implemented in the next pr). I will remove all of them out of this pr to avoid confusion.

2022-09-05 04:16 UTC, khoanguyen-saritasa commented on apps/react/src/hooks/useEffectSkipFirstRender.ts
> +    if (isFirstMounted.current < 2) {
My intention is to prevent the first search query API call when the app is first loaded. However, due to the strict mode which trigger the app to perform the callback inside normal useEffect 2 times, I have to skip 2 renders to prevent this behavior of strict mode.

2022-09-05 04:19 UTC, khoanguyen-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/AnimeSearch.tsx
> +  }, [debounceValue]);
Yeah sure I will add docs for this in the next pr since this one is just a test and I also removed it out of the codes.

2022-09-05 11:35 UTC, golovachev-yaroslav approved these changes

2022-09-08 08:28 UTC, pavelzadorin-saritasa requested changes

2022-09-08 08:28 UTC, pavelzadorin-saritasa commented on apps/react/src/hooks/useEffectSkipRender.ts
> +
No need to add an empty line after the JSDoc.
And you need a description of the parameters

2022-09-08 08:28 UTC, pavelzadorin-saritasa commented on apps/react/src/hooks/useSearch.ts
> +export const useSearch = () => {
And I don’t see at all that it would be used somewhere, then you need to remove it so as not to litter the code.

2022-09-12 06:00 UTC, golovachev-yaroslav approved these changes

2022-09-12 08:14 UTC, pavelzadorin-saritasa approved these changes

2022-09-13 06:38 UTC, artem-sotnichenko-saritasa commented on apps/react/src/services/searchParamService.ts
> +  readonly sortBy?: SortValue;
It's ok don't worry 🙂

2022-09-13 06:39 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-26 02:45 UTC, merged