Feature/JC19-483-react-anime-list-management
saritasa-nest/camp-js-2022-khoa-nguyen pull request #18
Opened 2022-09-05 02:32 UTC by khoanguyen-saritasa

2022-09-05 11:29 UTC, golovachev-yaroslav requested changes

2022-09-05 11:29 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeFilter/AnimeFilter.tsx
> +
PLease remove emty rrows between imports.

2022-09-05 11:29 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeSidebar/AnimeSidebar.module.css
> +  background-color: white;
PLease use css vars.

2022-09-05 11:29 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeSidebar/AnimeSidebar.tsx
> +    sx={{ padding: 0 }}
It would be better to mive it into css.

2022-09-06 05:06 UTC, golovachev-yaroslav approved these changes

2022-09-11 14:59 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-11 14:59 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/AppSelect/AppSelect.tsx
> +    setSelectedValue(value);
```suggestion
    setSelectedValue(value);
```

2022-09-11 14:59 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeFilter/AnimeFilter.tsx
> +    const _value = value as TypeModel[];
If you want to get `TypeModel[]` you should make parameters this type. And cast(`as`) or be use type guards in place where you call this function.

2022-09-12 03:30 UTC, khoanguyen-saritasa commented on apps/react/src/features/anime/components/AnimeFilter/AnimeFilter.tsx
> +    const _value = value as TypeModel[];
I'm sorry but I didn't get your point. Can you explain it more details?

2022-09-12 06:06 UTC, golovachev-yaroslav approved these changes

2022-09-12 17:51 UTC, pavelzadorin-saritasa commented on apps/react/src/hooks/useSearchParams.ts
> +import { useSearchParams } from 'react-router-dom';
please rename the file according to the hook

2022-09-12 17:51 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/AnimeSearch.tsx
> +  /** My intention is to prevent the first search query api call when the app is first loaded. */
this is the first time I'm faced with the need to skip the render, what is the reason for this decision? what problem arises if you do not skip the render?
in general, this is a very dubious decision, because there is no guarantee that the component will be rendered more than 1 time, it depends on a very large number of factors.

2022-09-13 04:02 UTC, khoanguyen-saritasa commented on apps/react/src/features/anime/components/AnimeSearch/AnimeSearch.tsx
> +  /** My intention is to prevent the first search query api call when the app is first loaded. */
The reason for this hook implementation is that I have already declared an useEffect hook in [AnimeInfinitiveScroll file](https://drive.google.com/file/d/1krj_SZQeAQV4KfaU4VtDX68wr89CGbG3/view?usp=sharing). This useEffect hook will perform the callback inside which is calling and fetching the anime list API for the first time. If I do not skip the first render of the useEffect in `AnimeSearch` feature, it will perform a redundant API call (it will fetch the anime list again in the first time of render). 
And of course, I can remove the API call in the useEffect at `AnimeInfinitiveScroll` file to avoid using this hook but I think it's a bit confusing because the API call of the list will be in `AnimeSearch` feature, which is not explicit and hard to maintain (for example if I need to remove `AnimeSearch` feature in the future, I have to re-implement the API call at `AnimeInfinitiveScroll` file. In this way, I only need to remove everything in `AnimeSearch` feature and everything will work greatly). 
What do you think? Please let me know if there are disadvantages in my approach and if there is a more efficient and suitable way in this case.

2022-09-26 02:42 UTC, merged