Feature/JC19-493-react-displaying-detail
saritasa-nest/camp-js-2022-khoa-nguyen pull request #19
Opened 2022-09-06 04:53 UTC by khoanguyen-saritasa

2022-09-06 05:09 UTC, golovachev-yaroslav requested changes

2022-09-06 05:09 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeDetail/AnimeDetail.tsx
> +          onClick={handleOpenImage}
Missed required `alt` attribute.
Also need to add `role="button"` is you need to use `img` as a button. Is it possible to use button instead of img?

2022-09-06 05:34 UTC, golovachev-yaroslav approved these changes

2022-09-06 08:33 UTC, golovachev-yaroslav approved these changes

2022-09-06 08:33 UTC, golovachev-yaroslav approved these changes

2022-09-11 15:28 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-12 06:06 UTC, golovachev-yaroslav approved these changes

2022-09-26 02:40 UTC, merged