Feature/JC19-356-authorization
saritasa-nest/camp-js-2022-khoa-nguyen pull request #2
Opened 2022-07-12 08:41 UTC by khoanguyen-saritasa

2022-07-14 05:49 UTC, elena-dragunova requested changes

2022-07-14 05:49 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.ts
> +if (form) {
Don't use implicit type-casting: https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting
Here and further

2022-07-14 05:49 UTC, elena-dragunova commented on apps/vanilla/src/pages/profile/index.html
> +    <button class="button">Sign out</button>
Add 'type' attribute to button.

2022-07-14 05:49 UTC, elena-dragunova commented on apps/vanilla/src/pages/signup/index.html
> +        <input class="form__item_input" data-type="email" required/>
Add 'type' attributes to inputs.

2022-07-14 08:36 UTC, artem-sotnichenko-saritasa requested changes

2022-07-14 10:23 UTC, maxineo requested changes

2022-07-14 10:23 UTC, maxineo commented on apps/vanilla/src/pages/index.ts
> +  window.location.href = PROFILE_URL;
I see that you are using it several times. I think it would be better to add some utility function for navigation.

2022-07-14 10:23 UTC, maxineo commented on apps/vanilla/src/pages/signup/signup.ts
> +  const inputLastName = form.querySelector('input[data-type=lastName]') as HTMLInputElement;
Use generic instead of type casting

2022-07-14 10:23 UTC, maxineo commented on apps/vanilla/src/pages/signup/signup.ts
> +          alert(result.detail);
The same with successful login alert.

2022-07-14 10:23 UTC, maxineo commented on apps/vanilla/src/pages/signup/signup.ts
> +      alert('Signup success!');
The same with successful login alert.

2022-07-14 10:23 UTC, maxineo commented on apps/vanilla/src/scripts/validate.ts
> +  confirmPasswordElement: HTMLInputElement;
Missing [readonly](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability)

2022-07-14 14:43 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/api/login.ts
> +export async function postUserLoginInfo(userLoginInfo: Login): Promise<Token | HttpError<ErrorLogin>> {
Post is not a good name. `login` suits more. Using `post` seems odd.

2022-07-14 14:44 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/api/register.ts
> +/** Post user information to register.
Also, don't forget about formatting
```suggestion
/** Register new user..
```

2022-07-14 14:45 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/api/verifyToken.ts
> +export async function postTokenToVerify(token: Token): Promise<Token | HttpError<ErrorToken | null>> {
```suggestion
export async function verifyToken(token: Token): Promise<Token | HttpError<ErrorToken | null>> {
```

2022-07-14 14:50 UTC, timofei-maximov-saritasa commented on libs/core/dtos/user.dto.ts
> +export interface ErrorUserDto {
If your error has user`s keys, then you can use `Record`([live demo](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4FgBQyyIcAthAFzLphSgDmA3AUQA5zroDuA9lACZUadEEwIBfAgTABPVigzQAolCh9kAXmQAlCHH48QAGxkAeXQj79TAawgyeMNJigAaZFD0HjM6rQYA2gC6AHwhQA)) or [mapped types](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html)

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/localStore/index.ts
> +}
Let's wrap it up inside namespace `LocalStorageService` and then rename function to avoid context duplication.
`setValue`, `getValue`, `remove`

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on libs/core/dtos/httpError.dto.ts
> +  readonly [key: string]: string[];
Missing readonly for array

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on libs/core/dtos/httpError.dto.ts
> +export interface Data {
Interface name is too generic

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/axios/index.ts
> +export const appAxios: AxiosInstance = axios.create({
You can omit type annotation. Typescript will infer type by itself

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/axios/index.ts
> +}
Let's improve auth flow by using [axios interceptors](https://axios-http.com/docs/interceptors)

2022-07-16 09:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/signup/signup.ts
> +        if (isValidPassword === false) {
There is no need for such validation for simple booleans
```suggestion
        if (!isValidPassword) {
```

2022-07-17 03:43 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/signup/signup.ts
> +        setValueToLocalStorage<Token>(TOKEN_KEY, result);
As I understand your comment, I should move all my logics involving with token into auth function right? Please correct me if I misunderstood your comment.

2022-07-17 13:32 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-17 13:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/signup/signup.ts
> +        inputPassword === null || inputLastName === null) {
```suggestion
      if (
        inputEmail === null ||
        inputFirstName === null ||
        inputConfirmPassword === null ||
        inputPassword === null ||
        inputLastName === null
      ) {
```

2022-07-17 13:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/services/api/verifyToken.ts
> +  }
You have code duplication. Perhaps move it out into funciton.

2022-07-17 15:46 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/services/api/getProfile.ts
> +    const result = await authAxios(token).get('/users/profile/');
Move this URL in constant, as you did in login and register files.

2022-07-17 15:46 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/services/api/verifyToken.ts
> + * @param token Token of verify.
```suggestion
 * @param token Token to verify.
```

2022-09-26 02:51 UTC, closed without merging