Feature/JC19-370-filter-by-type
saritasa-nest/camp-js-2022-khoa-nguyen pull request #3
Opened 2022-07-15 03:10 UTC by khoanguyen-saritasa

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa requested changes

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    if (container) {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    }
I seen this construction several times. To reduce code duplication, please extract it into a function.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> + */
Please format multiline jsdoc properly, first and last lines shouldn't have text.
```suggestion
/**
 * Render filter by type.
 * @param options Pagination options.
 */
```

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> +  if (selectType === null || selectType === undefined) {
In our company we prefer to check for undefined and null together, like so
```suggestion
  if (selectType == null) {
```

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> +  }
I think you should place this check in the beginning of the function.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderPagination.ts
> +  }
You don't really need to use `else if` when returning.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderPagination.ts
> +    });
Please fix indentation

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderPagination.ts
> +export async function renderListAndPaginationToUI(options: PaginationOptions): Promise<void> {
Usually function should do one thing at a time. So having "and" in your function name is a bad practice.
I suggest divide it into two functions.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +  }
Early return should be placed as early as possible.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +    });
Please fix indentation

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +    function getSelectOptions(): boolean {
You can use just a variable with a ternary operator here.

2022-07-16 09:22 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly modified: string;
It is strange that dates have different types.
If it not your typo, but api bug, consider reporting it in our slack camp chat.

2022-07-18 04:51 UTC, khoanguyen-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly modified: string;
It is type string for created date. This is my mistake.

2022-07-18 06:42 UTC, khoanguyen-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    }
I extracted it into function in feature show anime detail so can I skip the extraction in this feature?

2022-07-18 10:21 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderAnimeList.ts
> +    }
@khoanguyen-saritasa I think you can skip it in this PR.

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/constants/filterTypeOptions.ts
> +  value: TypeModel;
Don't forget to add readonly.

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/constants/filterTypeOptions.ts
> +export const FILTER_TYPE_OPTIONS: FilterType[] = [
Don't forget to add readonly for arrays too

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/initAnimeTable.ts
> +    totalPages: 0,
Be consistent and use constant as you do above.

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> +    FILTER_TYPE_OPTIONS[0].title);
```suggestion
  setDefaultSelected(selectType, FILTER_TYPE_OPTIONS.filter(item =>
    item.value === LocalStorageService.getValue<TypeModel>(KEY_TYPE))[0]?.title ??
    FILTER_TYPE_OPTIONS[0].title
  );
```

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderPagination.ts
> +        const strPage = item.childNodes[0].childNodes[0].nodeValue;
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> + */
Please format **all** multiline jsdoc properly
```suggestion
/**
 * Init and render sorting and ordering list, hence render corresponding list anime.
 * @param options Options of pagination.
 */
```

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +    .join('');
Be consistent
```suggestion
  const sortOptionHTML = SORT_OPTIONS.map(item => (
    `<option value="${item.title}">${item.title}</option>`
  )).join('');

  const orderOptionHTML = Object.keys(OrderOption).map(item => (
    `<option value ="${item}">${item}</option>`
  )).join('');
```

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +      activePage: 1,
Avoid "magic numbers", use constant

2022-07-18 10:45 UTC, artem-sotnichenko-saritasa commented on libs/core/enum/anime.ts
> +  // UNDEFINED = 'Undefined',
Don't store commented code in a repository

2022-07-20 17:33 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/constants/filterTypeOptions.ts
> +import { Type } from '@js-camp/core/enum';
Let's move it on top of file

2022-07-20 17:33 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/constants/filterTypeOptions.ts
> +  value: Type;
Missing readonly

2022-07-20 17:33 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/renderSortingAndOrdering.ts
> +  if (selectSort === null || selectSort === undefined) {
`querySelector` returns `Element | null`. There is no need to check if the value is `undefined`

2022-07-20 17:33 UTC, timofei-maximov-saritasa commented on libs/core/utils/index.ts
> +}
I don't think this function belongs here. It won't be used anywhere but vanilla app.

2022-07-20 17:33 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> +  });
Let's improve code readability by separating parts of this code with empty lines

2022-08-19 03:03 UTC, closed without merging