Feature/jc19 382 add searching
saritasa-nest/camp-js-2022-khoa-nguyen pull request #5
Opened 2022-07-18 03:52 UTC by LocTran-saritasa

Add searching

2022-07-18 05:50 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-18 05:50 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/utils/resetLocalStorage.ts
> +/** Check for null or undefined element.*/
It is not checking for anything, I suppose you forget to change it.

2022-07-19 07:43 UTC, panov-aleksey-saritasa requested changes

2022-07-19 07:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/constants/key.ts
> +export const KEY_SEARCHING = 'searching';
I think you should clarify that these keys are related to local storage, either use docs or wrap it in namespace

2022-07-19 07:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <div class="search__title">Search: </div>
Use [label tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) for this

2022-07-19 07:43 UTC, panov-aleksey-saritasa commented on libs/core/models/paginationOptions.ts
> +
Why do you mix up search string with pagination? Pagination and search string are unrelated things to each other

2022-07-24 14:40 UTC, maxineo approved these changes

2022-07-28 04:43 UTC, chernodub commented on apps/vanilla/src/global/base.css
> +  color: var(--font-color-primary);
Seems like you don't have such a property in `apps/vanilla/src/global/variables.css`

2022-07-28 04:43 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +        <input class="form__label-input" name="search" required />
Consider also specifying `type="search"` to improve the a11y and UX

2022-07-28 04:43 UTC, chernodub commented on apps/vanilla/src/scripts/renderSearching.ts
> +export function searchingHandler(options: AnimeListQueryOptions): void {
[Functions should be named with a verb](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions)

2022-07-28 04:43 UTC, chernodub commented on apps/vanilla/src/utils/resetLocalStorage.ts
> +  LocalStorageService.setValue(KEY_SEARCHING, '');
Seems like this function does a very specific thing, it only clears sort and searching. But the name is too generic. From the name, I would assume that all the values are going to be cleared.

2022-08-01 01:33 UTC, pavel-romanov8 approved these changes

2022-09-26 02:51 UTC, closed without merging