Feature/JC19-358-display-detail-film
saritasa-nest/camp-js-2022-khoa-nguyen pull request #6
Opened 2022-07-20 07:52 UTC by khoanguyen-saritasa

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa requested changes

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +  margin-top: 20px;
Avoid adding such margin to base styles. Most developers expect no margins on base components. 

For example, on one page you need top margin of 20px, on other 30px, and on other 0. In two cases you would need to overwrite it. Margin define how block positioned relatively to other blocks, so most of the time, margins need to be applied in the context.

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/home/index.html
> +        </div>
I think you're a bit confused with BEM. In this case, `div`, `label` and `select` have different purposes, so they can't be same element. But `select`s essentially do the same thing, but differ in options, so should use modifier.
```suggestion
        <div class="filter__item">
          <label class="filter__title">Sort by</label>
          <select class="filter__select filter__select_sort"></select>
        </div>
```

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/home/index.html
> +        </div>
Also please fix indentation, you can use prettier or vscode formatter.

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.ts
> +        }
wrong indentation

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/profile/index.html
> +    <div class="info">
Stick to BEM.

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/profile/profile.ts
> +  }
You can combine these early returns together with `||`.

2022-07-20 16:33 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/services/authorization/index.ts
> +    return true;
```suggestion
    return !(result instanceof HttpError);
```

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderDetailAnime.ts
> +  buttonTrailer?.addEventListener('click', () => renderPopupTrailer(anime.trailerYoutubeId));
check `buttonTrailer` too

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderDetailAnime.ts
> +      <button class="button button__popup_close">X</button>
Don't forget to add type to buttons.

One html-element can't be BEM-block and BEM-element (`button` and `button__popup_close`). I suggest rename class to just `button_close`.

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/renderFilterByType.ts
> +    item.value === searchParams.type)[0].title : FILTER_TYPE_OPTIONS[0].title) ;
I would format it this way.
```suggestion
  setDefaultSelected(
    selectType, searchParams.type != null ?
      FILTER_TYPE_OPTIONS.filter(item => item.value === searchParams.type)[0].title :
      FILTER_TYPE_OPTIONS[0].title
  );
```

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on libs/core/models/animeDetail.ts
> +  public readonly studios: readonly number[];
If it ids, I think you should name it `studioIds`, then you can remove `studiosData` to just `studios`.

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on libs/core/models/animeDetail.ts
> +  public readonly airing: boolean;
[Please use suffixes for boolean variables](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#is)

2022-07-21 10:18 UTC, artem-sotnichenko-saritasa commented on libs/core/models/animeDetail.ts
> +  public readonly studios: readonly number[];
I suggest using **indexed access type**, that way if studio id would change from number to string, you wouldn't need to change it everywhere by hand.
```suggestion
  public readonly studios: readonly Studio['id'][];
```

2022-07-25 06:35 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-25 06:35 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/app.component.html
> +</router-outlet>
It shouldn't be in this PR

2022-07-25 06:35 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/detail/detail.css
> +  margin-top: -20px;
Please don't use negative margin, it leads to bugs

2022-07-25 06:35 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/signup/signup.ts
> +  if (form !== null) {
I suggest to do early return, to remove one level of indentation.

2022-07-25 08:48 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/api/fetchAnimeDetail.ts
> +    const id = LocalStorageService.getValue<string>(KEY_ANIME);
What if user will try to see details directly? Let's use URL search params over local storage to implement navigation by id. This will allow users to share link with anime details

2022-07-25 08:48 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/validate.ts
> +  confirmPasswordElement: Readonly<HTMLInputElement>;
Missing readonly

2022-07-29 15:56 UTC, khoanguyen-saritasa commented on apps/vanilla/src/scripts/validate.ts
> +  confirmPasswordElement: Readonly<HTMLInputElement>;
If I put the normal readonly here, there is an error from TS saying that "'readonly' type modifier is only permitted on array and tuple literal types.". Therefore, I have to research another way to put the readonly into it and the way I found is the codes you see above. Is there another way to put the normal readonly for this specific case?

2022-09-26 02:51 UTC, closed without merging