Feature/JC19-401-angular-init-anime-table
saritasa-nest/camp-js-2022-khoa-nguyen pull request #7
Opened 2022-07-26 09:26 UTC by khoanguyen-saritasa

2022-07-26 13:48 UTC, kristinaSvobodinaSaritasa requested changes

2022-07-26 13:48 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +    this.anime.getAnimeList(this.defaultQuery).subscribe(data => {
Please, don't subscribe in the component, use async pipe. By the way, If you subscribe, you should don' t forget to unsubscribe when component destroy.

2022-07-27 04:55 UTC, timofei-maximov-saritasa requested changes
https://saritasa.slack.com/archives/C02UTQPRW7R/p1658889657459299

2022-07-27 04:55 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +  /** Get result of api call using async pipe method. */
What if we will use it just with `subscribe`? Let's update docstring and rename method

2022-07-27 04:55 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +    <tr *ngFor="let item of (result$ | async)?.results" class="table__row">
Missing `trackBy`

2022-07-27 04:55 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +        <img class= "table__row_item_thumb__img" src="{{item.image}}" alt="{{item.titleEnglish}}" />
Let's use angular [binding syntax](https://angular.io/guide/binding-syntax) over mustache syntax
```suggestion
        <img class= "table__row_item_thumb__img" [src]="item.image" [alt]="item.titleEnglish" />
```

2022-07-27 10:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.css
> +.table_row {
Is this a typo?
```suggestion
.table__row {
```

2022-07-27 10:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/app.component.css
> +}
Most of these classes are unused

2022-07-27 10:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  public result$: Observable<Pagination<Anime>> | undefined | null;
You can omit `undefined | null` by moving `this.result$ = this.anime.getAnime(this.defaultQuery);` to constructor

2022-07-27 10:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/services/anime.service.ts
> +  public constructor(private api: ApiService) {
Missing readonly

2022-07-28 05:01 UTC, TienLuu-Saritasa requested changes

2022-07-28 05:12 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/utils/index.ts
> +export function setDefaultSelected(selectElement: HTMLSelectElement, defaultValue: string): void {
When you approach to seperate util functions in some groups, I think we should move it in seperated file (example: handleDom.ts). And keep the index.ts just exports those utils

2022-07-28 06:28 UTC, thanhnguyen-saritasa commented on apps/angular/src/app/services/api.service.ts
> +  public constructor(private api: HttpClient) { }
I think parameter name 'api' could change to 'httpClient' is better.
So it would have more meaning clearly.

2022-07-28 06:34 UTC, thanhnguyen-saritasa commented on apps/angular/src/app/services/api.service.ts
> +  public constructor(private api: HttpClient) { }
And please add 'readonly' because we do not want to modify it 
Reference document: 
https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties

2022-07-29 04:54 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  }
If you are not going to use `animeService` outside of constructor, then you can omit access modifier 
```suggestion
  public constructor(animeService: AnimeService) {
    this.result$ = animeService.getAnimeList(this.defaultQuery);
  }
```
Otherwise, please add readonly
```suggestion
  public constructor(private readonly animeService: AnimeService) {
    this.result$ = this.animeService.getAnimeList(this.defaultQuery);
  }
```

2022-07-29 04:54 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/api.service.ts
> +   *  Api service constructors.
Extra space. Please, check it everywhere
```suggestion
   * Api service constructors.
```

2022-07-29 04:54 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.spec.ts
> +});
Do you really need this tests?

2022-07-29 04:54 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +    <tr *ngFor="let item of (result$ | async)?.results; trackBy: trackByAnime" class="table__row">
You can use `ngIf` to get rid of this optional chaining. 
If you don't need new element in your dom, you can use `ng-container`
https://angular.io/api/core/ng-container#with-ngifs

2022-07-29 17:18 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.spec.ts
> +});
This file is redundant  because I forgot to config nx not automatically generating test.

2022-08-08 00:55 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-08 00:55 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  public readonly result$: Observable<Pagination<Anime>>;
Please use a better name, for example `animeList$`

2022-08-08 00:55 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +   */
You can omit jsdoc for constructors

2022-08-08 00:55 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/api.service.ts
> +    }
Because we work with observable, `try catch` won't work. Read about `catch` operator.

2022-09-26 02:50 UTC, closed without merging